=== PathanAmanKhan47/EP-SKILLING/Student.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT students (student+)>
<!ELEMENT student (number,name,e-mail,marks,class)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT e-mail (#PCDATA)>
<!ELEMENT marks (#PCDATA)>
<!ELEMENT class  (#PCDATA)>

=== PathanAmanKhan47/EP-SKILLING/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "student.dtd">
<students>
<student>
<number>
190031275
</number>
<name>
Aman
</name>
<e-mail>
abc@gmail.com
</e-mail>
<marks>
90
</marks>
<class>
X1
</class>
</student>
<student>
<number>
190031909
</number>
<name>
Sohail
</name>
<e-mail>
pqr@gmail.com
</e-mail>
<marks>
91
</marks>
<class>
1X
</class>
</student>
<student>
<number>
190031987
</number>
<name>
Ravi
</name>
<e-mail>
xyz@gmail.com
</e-mail>
<marks>
93
</marks>
<class>
X
</class>
</student>
<student>
<number>
190031454
</number>
<name>
Sam
</name>
<e-mail>
efg@gmail.com
</e-mail>
<marks>
90
</marks>
<class>
X11
</class>
</student>
<student>
<number>
190031321
</number>
<name>
Kim
</name>
<e-mail>
opo@gmail.com
</e-mail>
<marks>
92
</marks>
<class>
V1
</class>
</student>
</students>
